
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS
, TO_CHAR(UGR.CREATED_DATE, 'YYYY-MM-dd')
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID 
WHERE TO_CHAR(UGB.CREATED_DATE, 'YYYY-MM-dd') LIKE '2022-10%'
ORDER BY UGR.CREATED_DATE, UGB.TITLE